DROP MATERIALIZED VIEW IF EXISTS mv_portfolio_final_pnl;
--DROP MATERIALIZED VIEW IF EXISTS mv_portfolio_exit_legs;
DROP MATERIALIZED VIEW IF EXISTS mv_portfolio_mtm_pnl;
DROP MATERIALIZED VIEW IF EXISTS mv_ALL_ENTRIES_sl_tracking_adjusted;
DROP MATERIALIZED VIEW IF EXISTS mv_entry_Leg_live_prices;
DROP MATERIALIZED VIEW IF EXISTS mv_all_legs_pnl_entry_round_REENTRY;
DROP MATERIALIZED VIEW IF EXISTS mv_reentry_entry_and_hedge_legs;
DROP MATERIALIZED VIEW IF EXISTS mv_reentry_base_strike_selection;
DROP MATERIALIZED VIEW IF EXISTS mv_reentry_triggered_breakouts ;
DROP MATERIALIZED VIEW IF EXISTS mv_all_legs_pnl_entry_round1;
DROP MATERIALIZED VIEW IF EXISTS mv_entry_and_hedge_legs;
DROP MATERIALIZED VIEW IF EXISTS mv_base_strike_selection;
DROP MATERIALIZED VIEW IF EXISTS mv_ranked_breakouts_with_rounds;
DROP MATERIALIZED VIEW IF EXISTS mv_all_5min_breakouts;
DROP MATERIALIZED VIEW IF EXISTS mv_ha_big_candle;
DROP MATERIALIZED VIEW IF EXISTS mv_ha_small_candle;
--DROP MATERIALIZED VIEW IF EXISTS mv_ha_15min_candle;
--DROP MATERIALIZED VIEW IF EXISTS mv_ha_5min_candle;

REFRESH MATERIALIZED VIEW mv_ha_big_candle;
REFRESH MATERIALIZED VIEW mv_ha_small_candle;
CALL refresh_mv_ha_big_candle('default');
CALL refresh_mv_ha_small_candle('default');
REFRESH MATERIALIZED VIEW mv_all_5min_breakouts;
REFRESH MATERIALIZED VIEW mv_ranked_breakouts_with_rounds;
REFRESH MATERIALIZED VIEW mv_base_strike_selection;
REFRESH MATERIALIZED VIEW mv_entry_and_hedge_legs;
REFRESH MATERIALIZED VIEW mv_all_legs_pnl_entry_round1;
DELETE FROM strategy_leg_book;
CALL insert_sl_legs_into_book();
REFRESH MATERIALIZED VIEW mv_reentry_triggered_breakouts;
REFRESH MATERIALIZED VIEW mv_reentry_base_strike_selection;
REFRESH MATERIALIZED VIEW mv_reentry_entry_and_hedge_legs;
REFRESH MATERIALIZED VIEW mv_all_legs_pnl_entry_round_REENTRY ;
CALL sp_run_reentry_loop('default');
REFRESH MATERIALIZED VIEW mv_entry_Leg_live_prices;
REFRESH MATERIALIZED VIEW mv_ALL_ENTRIES_sl_tracking_adjusted;
REFRESH MATERIALIZED VIEW mv_portfolio_mtm_pnl;
--REFRESH MATERIALIZED VIEW mv_portfolio_exit_legs;
REFRESH MATERIALIZED VIEW mv_portfolio_final_pnl;